version: 2

sources: 
  - name: staging 
    database: quantum-balm-372420
    schema: trips_data_all

    tables: 
      - name: green_tripdata_partitioned
      - name: yellow_tripdata_partitioned
      